#!/usr/bin/env bash
#
# Uses the Dockerfile generated by s2i to assemble a new container image using buildah.
#

shopt -s inherit_errexit
set -eu -o pipefail

declare -r cur_dir="$(dirname ${BASH_SOURCE[0]})"

source "${cur_dir}/common.sh"
source "${cur_dir}/s2i-common.sh"

# loading buildah settings overwritting the full path to the container file
declare -x DOCKERFILE_FULL="${S2I_DOCKERFILE}"
source "${cur_dir}/buildah-common.sh"

phase "Building the Dockerfile '${DOCKERFILE_FULL}' with buildah"
exec ${cur_dir}/buildah-bud.sh
